In [21]:
import numpy as np
import math
def forward_kinematics(joints,robot_type): #left to implement
		if robot_type == 'bisturi':
			EF = 0.15+0.16
		elif robot_type == 'camera':
			EF = 0.18
		else:
			raise TypeError('Invalid robot_type') 
		theta1,theta2,theta3,theta4,theta5 = joints

		T_01 = np.matrix([[math.cos(theta1),math.sin(theta1),0,0],
					[math.sin(theta1),math.cos(theta1),0,0],
					[0,0,1,0],
					[0,0,0,1]])
		T_12 = np.matrix([[1,0,0,0.05],
					[0,1,0,0],
					[0,1,0,3585],
					[0,0,0,1]])
		T_23 = np.matrix([[math.cos(theta2),-math.sin(theta2),0,0],
					[0,0,1,0],
					[-math.sin(theta2),-math.cos(theta2),0,0],
					[0,0,0,1]])
		T_34 = np.matrix([[0,1,0,0],
					[-1,0,0,0],
					[0,0,1,0.135],
					[0,0,0,1]])
		T_45 = np.matrix([[math.cos(theta3),-math.sin(theta3),0,0.3],
					[math.sin(theta3),math.cos(theta3),0,0],
					[0,0,1,0],
					[0,0,0,1]])
		T_56 = np.matrix([[math.cos(theta4),-math.sin(theta4),0,0.35],
					[math.sin(theta4),math.cos(theta4),0,0],
					[0,0,1,0],
					[0,0,0,1]])
		T_67 = np.matrix([[0,-1,0,0],
					[1,0,0,0],
					[0,0,1,0],
					[0,0,0,1]])
		T_78 = np.matrix([[math.cos(theta5),-math.sin(theta5),0,0],
					[0,0,-1,0],
					[math.sin(theta5),math.cos(theta5),0,0],
					[0,0,0,1]])
		T_89 = np.matrix([[1,0,0,0],
					[0,1,0,0],
					[0,0,1,EF],
					[0,0,0,1]])
		
		
		T = T_01.dot(T_12).dot(T_23).dot(T_34).dot(T_45).dot(T_56).dot(T_67).dot(T_78).dot(T_89)

		return T

In [37]:
T = forward_kinematics([1,2,3,4,5],'bisturi')
print(T)
pos = T[0:3,3]
print(pos.tolist()[0])

[[-9.46549814e-01 -2.33371287e-01  2.22668568e-01  1.75691454e-01]
 [-7.35589867e-01 -5.81934011e-01  3.46785748e-01  1.69644729e-01]
 [-9.58924275e-01  2.83662185e-01  0.00000000e+00  3.58513500e+03]
 [ 0.00000000e+00  0.00000000e+00  0.00000000e+00  1.00000000e+00]]
[0.17569145434771]
